=== Keelan-Matthews/xml-assignments/Theme Assignments/a1/TA.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT meal ((breakfast | lunch | dinner)*,dessert)>

<!ELEMENT breakfast (name,cost)>
<!ATTLIST breakfast id ID #REQUIRED>

<!ELEMENT lunch (name,cost)>
<!ATTLIST lunch id ID #REQUIRED 
                after IDREF #IMPLIED>

<!ELEMENT dinner (name,cost)>
<!ATTLIST dinner id ID #REQUIRED>

<!ELEMENT dessert EMPTY>

<!ELEMENT name (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ATTLIST cost cur (ZAR|USD) #REQUIRED>

=== Keelan-Matthews/xml-assignments/Theme Assignments/a1/validfile.xml
<?xml version="1.0"?>

<!DOCTYPE meal SYSTEM "TA.dtd">
<meal>
	<!-- the <meal> element can hold multiple <breakfast>, <lunch> and <dinner> element in no specfic order-->
	<!-- <meal> element can also be completely empty-->

	<!-- <breakfast>, <lunch> and <dinner> all follow the same rules-->
	<!-- they each contain two element <name> and <cost> these element has to appear in order-->
	<breakfast id="b102">
	<!-- @id has to be a unique identifier-->
		<name>Toast</name> <!-- Plain text-->
		<cost cur="ZAR">30</cost> <!-- Plain text-->
		<!-- 
			the attribute @cur has to appear
			it can either be ZAR or USD 
		-->
	</breakfast>

	<lunch id="l103" after="b102">
	<!-- element can hold an optional attribute @after-->
	<!-- @after need to reference an existing id in the document-->
		<name>Pasta</name>
		<cost cur="ZAR">50</cost>
	</lunch>

	<dinner id="d104">
		<name>Steak</name>
		<cost cur="ZAR">90</cost>
	</dinner>

	<!-- after many <breakfast>, <lunch> and <dinner> a single <dessert> may appear--> 
	<!-- <dessert> is an empty tag-->
	<dessert></dessert>
</meal>
